# Generated by Django 5.0 on 2024-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptInterface', '0003_alter_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
