# Generated by Django 5.0 on 2024-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptInterface', '0004_chatsession_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
