# Generated by Django 5.0 on 2024-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptInterface', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='pre_messages',
            field=models.TextField(blank=True, help_text='Enter pre-messages (JSON format) for the model.'),
        ),
    ]
