# Generated by Django 4.2.1 on 2024-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptInterface', '0008_documenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenter',
            name='final_documentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='final_runbook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='functions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='general_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='raw_dependencies_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='raw_functions_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='raw_general_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='raw_notes_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='raw_runbook_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='summarized_dependencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenter',
            name='summarized_runbook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
