# Generated by Django 5.0 on 2024-01-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('read_status', models.BooleanField(default=False)),
            ],
        ),
    ]
