# Generated by Django 4.2.8 on 2024-01-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_account_fieldentry_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('transportation', 'Transportation'), ('food', 'Food'), ('entertainment', 'Entertainment'), ('takeout', 'Takeout'), ('supplies', 'Supplies')], max_length=50, unique=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('categories', models.ManyToManyField(to='mainapp.budgetcategory')),
            ],
        ),
    ]
