# Generated by Django 4.2.8 on 2024-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_budgetcategory_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='monthly_limit',
            new_name='weekly_limit',
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
