# Generated by Django 4.2.8 on 2024-01-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_monthly_limit_budgetcategory_weekly_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='weekly_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='weekly_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(choices=[('transportation', 'Transportation'), ('food', 'Food'), ('entertainment', 'Entertainment'), ('takeout', 'Takeout'), ('supplies', 'Supplies')], max_length=50),
        ),
    ]
