# Generated by Django 4.2.8 on 2024-01-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_account_weekly_debt_account_weekly_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='accounted_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(choices=[('transportation', 'Transportation'), ('food', 'Food'), ('entertainment', 'Entertainment'), ('takeout', 'Takeout'), ('supplies', 'Supplies')], max_length=50, unique=True),
        ),
    ]
