# Generated by Django 4.2.8 on 2024-01-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_fieldentry_accounted_for_alter_budgetcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldentry',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
