# Generated by Django 4.2.8 on 2024-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_fieldentry_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week', models.DateTimeField(blank=True, null=True)),
                ('end_week', models.DateTimeField(blank=True, null=True)),
                ('transportation_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entertainment_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entertainment_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('takeout_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('takeout_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplies_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplies_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
