# Generated by Django 4.2.8 on 2024-01-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_budgetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='bar_color',
            field=models.CharField(default='bg-blue-600', max_length=50),
        ),
    ]
