# Generated by Django 4.2.1 on 2024-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_generalnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overspenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
