# Generated by Django 4.2.8 on 2024-03-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_tool_path_tool_title_alter_tool_associated_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('Insight', 'Insight'), ('Technical', 'Technical'), ('Creative', 'Creative'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
