# Generated by Django 4.2.8 on 2024-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_prompt_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('use_embeddings', models.BooleanField(default=False)),
                ('web_access', models.BooleanField(default=False)),
                ('pre_feed_context', models.JSONField(blank=True, null=True)),
                ('default_env_path', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(default='gpt-3.5-turbo-0613', max_length=50)),
                ('tools', models.ManyToManyField(blank=True, to='education.tool')),
            ],
        ),
    ]
