# Generated by Django 4.2.8 on 2024-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='path',
            field=models.FilePathField(blank=True, help_text='Path to the tool', match='.*', null=True, path='C:\\Users\\aleja\\OneDrive\\Escritorio\\PersonalWeb\\webPerson\\tools_main_repo/', recursive=True),
        ),
    ]
