# Generated by Django 4.2.8 on 2024-03-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_tool_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='associated_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='education.problem'),
        ),
    ]
