# Generated by Django 4.2.1 on 2024-04-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_book_page_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='index_contents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
