# Generated by Django 4.2.1 on 2024-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_book_index_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedded',
            field=models.BooleanField(default=False, help_text='If the book is embedded in the website, set this to True.'),
        ),
    ]
