# Generated by Django 4.2.1 on 2024-05-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_transcript_summarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
