# Generated by Django 4.2.8 on 2024-05-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_lessonembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonembedding',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
