# Generated by Django 4.2.8 on 2024-05-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_alter_lessonembedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
