# Generated by Django 4.2.8 on 2024-05-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_alter_transcript_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='related_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='education.lesson'),
        ),
    ]
