# Generated by Django 4.2.8 on 2024-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_notes_related_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
