# Generated by Django 4.2.8 on 2024-05-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_notes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assignments/answers/'),
        ),
    ]
