# Generated by Django 4.2.8 on 2024-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_assignment_answer_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chapter_page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
