# Generated by Django 4.2.8 on 2024-05-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_lesson_chapter_page_number_lesson_chapter_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, help_text='This is like Q1, Q2, etc.', max_length=10, null=True)),
                ('question', models.TextField(blank=True, help_text='An optional entry for the question, it is simply the question itself.', null=True)),
                ('answer', models.FileField(blank=True, help_text='An entry for the answer to the question in pdf form.', null=True, upload_to='assignments/answers/sectioned/')),
                ('related_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.assignment')),
            ],
        ),
    ]
