# Generated by Django 4.2.1 on 2024-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
