# Generated by Django 4.2.8 on 2024-06-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_concept_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
