# Generated by Django 4.2.8 on 2024-06-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0028_concept_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='description',
            new_name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='active',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='title',
        ),
        migrations.AddField(
            model_name='prompt',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('raw_latex', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='study_sheets/')),
                ('class_belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sheets', to='education.class')),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='education.template'),
        ),
    ]
