# Generated by Django 4.2.8 on 2024-08-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_template_alter_prompt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='class_books/')),
                ('latex_content', models.TextField(blank=True, null=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='class_books', to='education.class')),
            ],
        ),
    ]
